datasource:
  jdbcURL: jdbc:h2:mem:mydb;MODE=Oracle;DB_CLOSE_ON_EXIT=FALSE;
  username: sa
  password:
  driverclass: org.h2.Driver
  driverClassName: org.h2.DriverdriverClassName
spring:
  h2:
    console.enabled: true
    show_sql: true
  datasource:
    url: jdbc:h2:mem:mydb;MODE=Oracle;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
    driverClassName: org.h2.Driver
    driverclass: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect #com.github.rx.commons.Oracle10gDialectWithXMLType
    #database: ORACLE
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.H2Dialect  #eu.yayi.commons.Oracle10gDialectWithXMLType
        #org.hibernate.dialect.H2Dialect #org.hibernate.dialect.Oracle10gDialect #eu.yayi.commons.Oracle10gDialectWithXMLType
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    generate-ddl: true
    show_sql: true
    default_schema: PUBLIC
    #org.hibernate.dialect.Oracle10gDialect
    #com.github.rx.commons.OracleDialectExtension
    #application.yaml.commons.Oracle10gDialectWithXMLType
    #org.hibernate.dialect.H2Dialect
